/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_duomai_threekingdoms_JniManager */

#ifndef _Included_com_duomai_threekingdoms_JniManager
#define _Included_com_duomai_threekingdoms_JniManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_duomai_threekingdoms_JniManager
 * Method:    RechargeVerification
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_duomai_threekingdoms_JniManager_RechargeVerification
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
